version: 2

project_name: bubbleMonitor

before:
  hooks:
    - go generate ./...

builds:
  - id: bubbleMonitor
    main: ./cmd/bub
    binary: bub
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: binaries
    format: binary
  - id: archives
    formats:
      - tar.gz
      - zip
    wrap_in_directory: true
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'

checksum:
  name_template: 'checksums.txt'

release:
  github:
    owner: N1xev
    name: bubbleMonitor
  draft: false
  prerelease: auto
  name_template: '{{.Tag}}'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^refactor:'
